version: "3.8"

x-common-variables:
  read-only-workdir: &read-only-workdir
    type: bind
    source: .
    target: /workdir
    read_only: true
  read-write-workdir: &read-write-workdir
    type: bind
    source: .
    target: /workdir
    read_only: false

services:
  hcl-formatter:
    image: docker.cloudsmith.io/grapl/raw/hcl-formatter:latest
    command: format
    volumes:
      - *read-write-workdir

  hcl-linter:
    image: docker.cloudsmith.io/grapl/raw/hcl-formatter:latest
    command: lint
    volumes:
      - *read-only-workdir

  hadolint:
    image: hadolint/hadolint:2.6.0-debian
    command: [ "hadolint", "Dockerfile" ]
    working_dir: /workdir
    volumes:
      - *read-only-workdir
